from selenium.webdriver.common.by import By


closeup_icon_locator = (By.XPATH, "//span[@role='presentation']")
source_city_locator = (By.XPATH, "//span[text()='From']//following-sibling::p")
dest_city_locator = (By.XPATH, "//span[text()='To']//following-sibling::p")
source_city_input_locator =(By.XPATH, "//span[text()='From']//following-sibling::input")
dest_city_input_locator = (By.XPATH, "//span[text()='To']//following-sibling::input")
departure_date_arrow_locator = (By.XPATH, "//span[text()='Departure']//parent::div")
#date_value_locator= (By.XPATH, "//div[@class='DayPicker-Day' and @aria-disabled='false']")
traveller_locator = (By.XPATH, "//span[contains(text(),'Travellers')]//parent::div")
search_flight_button_locator=(By.XPATH,"//span[contains(text(),'SEARCH FLIGHTS')]")
#adult_add_count_locator = (By.XPATH, "//p[contains(text(),'Adults')]//parent::div//following-sibling::div/span[3]")
adult_add_count_locator = (By.XPATH, "//span[contains(text(),'1')]//following-sibling::span")
children_add_locator = (By.XPATH, "//p[contains(text(),'Children')]//parent::div//following-sibling::div/span[3]")
infant_add_locator = (By.XPATH, "//p[contains(text(),'Infants')]//parent::div//following-sibling::div/span[3]")
economy_locator= (By.XPATH, "//li[text()='economy']")
done_button_locator=(By.XPATH, "//a[text()='Done']")
traveller_dropdown_locator=(By.XPATH, "//p[contains(text(),'Adult')]")
deny_button =(By.XPATH, "//button[@id='deny']")
iframe_prompt_locator=(By.ID, "webpush-onsite")
got_it_locator =(By.XPATH, "//span[text()='GOT IT']//parent::div//following-sibling::span")
flight_name_locator =(By.XPATH, "//p[text()='6E 5322']//parent::div/p[1]")
#view_fares_locator=(By.XPATH, "//span[text()='VIEW FARES']")
#view_fare_button_locator = (By.XPATH, "//button[@id='bookbutton-RKEY:d4b07c63-d492-4699-bd10-7ef51e84815d:2_0']")
view_fare_button_locator = (By.XPATH, "//p[text()='IndiGo']//ancestor::div[@class='makeFlex']//following-sibling::div[contains(@class,'priceSection')]//button")
#view_fare_button_locator=(By.XPATH, "//p[text()='IndiGo']//ancestor::div//following::button/span[@data-test='component-buttonText']")
#fare_done_button=(By.XPATH, "//p[text()='FARE BY Goibibo']//preceding::div//button[text()='BOOK NOW']")
fare_done_button=(By.XPATH, "//p[text()='FLEXI PLUS']//preceding::div//button[text()='BOOK NOW']")
user_consent_locator=(By.XPATH, "//button[@type='USERCONSENT']")
fare_summary_list_locator=(By.XPATH, "//span[@data-test='component-total']")
total_amount_fare_locator=(By.XPATH, "//span[@data-test='component-tot_fare']")
okay_gotit_locator = (By.XPATH, "//button[contains(text(),'OKAY, GOT IT!')]")